version: '3.8'

services:
  flask_app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../app:/app
    expose:
      - "5000"
    networks:
      - app_network

  # 'services' 아래에 2칸 들여쓰기
  nginx:
    # 'nginx' 아래에 2칸 더 들여쓰기
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app
    networks:
      - app_network

  # 'services' 아래에 2칸 들여쓰기
  postgres:
    # 'postgres' 아래에 2칸 더 들여쓰기
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  # 'services' 아래에 2칸 들여쓰기
  mongo:
    # 'mongo' 아래에 2칸 더 들여쓰기
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

# 파일 최상단에 위치
networks:
  app_network:
    driver: bridge

# 파일 최상단에 위치
volumes:
  postgres_data:
  mongo_data: