version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=feel_log_user
      - POSTGRES_PASSWORD=feel_log_password
      - POSTGRES_DB=feel_log_db
    ports:
      - "5432:5432"
    volumes:
      - feel-log-db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feel_log_user -d feel_log_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=feel_log_db
      - POSTGRES_USER=feel_log_user
      - POSTGRES_PASSWORD=feel_log_password

volumes:
  feel-log-db: